import { Archivo } from "next/font/google";
import "./globals.css";

const archivo = Archivo({
  subsets: ["latin"],
});

export const metadata = {
  title: "Next Js Front End",
  description: "Generated by Next Js Front End",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={archivo.className}>
      <body className="antialiased">{children}</body>
    </html>
  );
}
