import { Archivo } from "next/font/google";
import "./globals.css";

const archivo = Archivo({
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={archivo.className}>
            <body className="antialiased">{children}</body>
        </html>
    );
}
